name: Build Gradle Project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    env:
      DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
      DATASOURCE_ADMIN: ${{ secrets.DATASOURCE_ADMIN }}
      DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
      ENVIRONMENT: prod
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper for prod profile
        run: ./gradlew build -Penv=${ENVIRONMENT}